
/*******************************************************************************
** exvr-designer                                                              **
** No license (to be defined)                                                 **
** Copyright (c) [2018] [Florian Lance][EPFL-LNCO]                            **
********************************************************************************/

#pragma once

// Qt
#include <QApplication>
#include <QStandardPaths>

// local
#include "qt_str.hpp"


namespace tool::ex{

struct Paths{

    static void initialize_paths();

    // application
    static inline QString exeDir = "";
    static inline QString exe = "";

    // exp launcher
    static inline QString expLauncherDir = "";
    static inline QString expLauncherVR = "";

    // logs
    static inline QString logsDir = "";
    static inline QString designerLogFile = "";
    static inline QString expLogFile = "";

    // data
    static inline QString dataDir = "";
    // # temp
    static inline QString tempDir = "";
    static inline QString tempExp = "";
    static inline QString tempInstance = "";

    // experiments
    static inline QString expDir = "";

    // resources
    // # assets bundles
    static inline QString assetsBundlesDir = "";
    // # python scripts
    static inline QString scriptsPythonDir = "";
    static inline QString templatePythonScript = "";
    // # C# scripts
    static inline QString scriptsCSharpDir = "";
    static inline QString templateCSharpScript = "";

    // documentation
    static inline QString documentationDir = "";
    static inline QString generalDocFile = "";
    static inline QString experimentDocFile = "";
    static inline QString elementsDocFile = "";
    static inline QString randomizationDocFile = "";
    static inline QString componentsDocDir = "";
    static inline QString connectorsDocDir = "";
    static inline QString interfaceDocFile = "";
    static inline QString expLauncherDocFile = "";
    static inline QString logsDocFile = "";
    static inline QString settingsDocFile = "";

    // system
    static inline QString documentsDir = "";
    static inline QString desktopDir = "";
};

}

//QStandardPaths::standardLocations(QStandardPaths::AppDataLocation).value(0);


//Path type	macOS	Windows
//DesktopLocation	"~/Desktop"	"C:/Users/<USER>/Desktop"
//DocumentsLocation	"~/Documents"	"C:/Users/<USER>/Documents"
//FontsLocation	"/System/Library/Fonts" (not writable)	"C:/Windows/Fonts" (not writable)
//ApplicationsLocation	"/Applications" (not writable)	"C:/Users/<USER>/AppData/Roaming/Microsoft/Windows/Start Menu/Programs"
//MusicLocation	"~/Music"	"C:/Users/<USER>/Music"
//MoviesLocation	"~/Movies"	"C:/Users/<USER>/Videos"
//PicturesLocation	"~/Pictures"	"C:/Users/<USER>/Pictures"
//TempLocation	randomly generated by the OS	"C:/Users/<USER>/AppData/Local/Temp"
//HomeLocation	"~"	"C:/Users/<USER>"
//DataLocation	"~/Library/Application Support/<APPNAME>", "/Library/Application Support/<APPNAME>". "<APPDIR>/../Resources"	"C:/Users/<USER>/AppData/Local/<APPNAME>", "C:/ProgramData/<APPNAME>", "<APPDIR>", "<APPDIR>/data", "<APPDIR>/data/<APPNAME>"
//CacheLocation	"~/Library/Caches/<APPNAME>", "/Library/Caches/<APPNAME>"	"C:/Users/<USER>/AppData/Local/<APPNAME>/cache"
//GenericDataLocation	"~/Library/Application Support", "/Library/Application Support"	"C:/Users/<USER>/AppData/Local", "C:/ProgramData", "<APPDIR>", "<APPDIR>/data"
//RuntimeLocation	"~/Library/Application Support"	"C:/Users/<USER>"
//ConfigLocation	"~/Library/Preferences"	"C:/Users/<USER>/AppData/Local/<APPNAME>", "C:/ProgramData/<APPNAME>"
//GenericConfigLocation	"~/Library/Preferences"	"C:/Users/<USER>/AppData/Local", "C:/ProgramData"
//DownloadLocation	"~/Downloads"	"C:/Users/<USER>/Documents"
//GenericCacheLocation	"~/Library/Caches", "/Library/Caches"	"C:/Users/<USER>/AppData/Local/cache"
//AppDataLocation	"~/Library/Application Support/<APPNAME>", "/Library/Application Support/<APPNAME>". "<APPDIR>/../Resources"	"C:/Users/<USER>/AppData/Roaming/<APPNAME>", "C:/ProgramData/<APPNAME>", "<APPDIR>", "<APPDIR>/data", "<APPDIR>/data/<APPNAME>"
//AppLocalDataLocation	"~/Library/Application Support/<APPNAME>", "/Library/Application Support/<APPNAME>". "<APPDIR>/../Resources"	"C:/Users/<USER>/AppData/Local/<APPNAME>", "C:/ProgramData/<APPNAME>", "<APPDIR>", "<APPDIR>/data", "<APPDIR>/data/<APPNAME>"
//AppConfigLocation	"~/Library/Preferences/<APPNAME>"	"C:/Users/<USER>/AppData/Local/<APPNAME>", "C:/ProgramData/<APPNAME>"

//Path type	Linux
//DesktopLocation	"~/Desktop"
//DocumentsLocation	"~/Documents"
//FontsLocation	"~/.fonts"
//ApplicationsLocation	"~/.local/share/applications", "/usr/local/share/applications", "/usr/share/applications"
//MusicLocation	"~/Music"
//MoviesLocation	"~/Videos"
//PicturesLocation	"~/Pictures"
//TempLocation	"/tmp"
//HomeLocation	"~"
//DataLocation	"~/.local/share/<APPNAME>", "/usr/local/share/<APPNAME>", "/usr/share/<APPNAME>"
//CacheLocation	"~/.cache/<APPNAME>"
//GenericDataLocation	"~/.local/share", "/usr/local/share", "/usr/share"
//RuntimeLocation	"/run/user/<USER>"
//ConfigLocation	"~/.config", "/etc/xdg"
//GenericConfigLocation	"~/.config", "/etc/xdg"
//DownloadLocation	"~/Downloads"
//GenericCacheLocation	"~/.cache"
//AppDataLocation	"~/.local/share/<APPNAME>", "/usr/local/share/<APPNAME>", "/usr/share/<APPNAME>"
//AppLocalDataLocation	"~/.local/share/<APPNAME>", "/usr/local/share/<APPNAME>", "/usr/share/<APPNAME>"
//AppConfigLocation	"~/.config/<APPNAME>", "/etc/xdg/<APPNAME>"
